Cours:
    type: entity
    table: cours
    id:
        idcours:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        lieu:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        matiere:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        dure:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        dateDebut:
            type: date
            nullable: true
            comment: ''
            column: date_debut
        dateFin:
            type: date
            nullable: true
            comment: ''
            column: date_fin
    lifecycleCallbacks: {  }
