Role:
    type: entity
    table: role
    id:
        idrole:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        habilitation:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToMany:
        utilisateurutilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: rolerole
            joinTable:
                name: role_has_utilisateur
                joinColumns:
                    -
                        name: role_idrole
                        referencedColumnName: idrole
                inverseJoinColumns:
                    -
                        name: utilisateur_idutilisateur
                        referencedColumnName: idutilisateur
            orderBy: null
    lifecycleCallbacks: {  }
