index:
    path:    /
    defaults: { _controller: PlanningUserBundle:Planning:accueil }

home:
    path:    /Accueil
    defaults: { _controller: PlanningUserBundle:Planning:accueil }
    
planning:
    path:    /Planning
    defaults: { _controller: PlanningUserBundle:Planning:planning }
    
essaie:
    path:    /ajouter
    defaults: { _controller: PlanningUserBundle:Cours:ajoutercours }
    
test:
    path:    /test
    defaults: { _controller: PlanningUserBundle:Planning:annuel}
    
gestion_promo:
    path:    /g_promo
    defaults: { _controller: PlanningUserBundle:Planning:gestionpromo}