index:
    path:    /
    defaults: { _controller: PlanningUserBundle:Planning:accueil }

home:
    path:    /Accueil
    defaults: { _controller: PlanningUserBundle:Planning:accueil }
    
planning:
    path:    /Planning
    defaults: { _controller: PlanningUserBundle:Planning:planning }
    
essaie:
    path:    /ajouter
    defaults: { _controller: PlanningUserBundle:Cours:ajoutercours }
    
test:
    path:    /test
    defaults: { _controller: PlanningUserBundle:Planning:annuel}
    
gestion_promo:
    path:    /g_promo
    defaults: { _controller: PlanningUserBundle:Planning:gestionpromo}
    
gestion_professeur:
    path:    /g_professeur
    defaults: { _controller: PlanningUserBundle:Planning:gestionprofesseur}
    
gestion_eleve:
    path:    /g_eleve
    defaults: { _controller: PlanningUserBundle:Planning:gestioneleve}
    
gestion_matiere:
    path:    /g_matiere
    defaults: { _controller: PlanningUserBundle:Planning:gestionmatiere}
    
gestion_site:
    path:    /g_site
    defaults: { _controller: PlanningUserBundle:Planning:gestionsite}
    
gestion_salle:
    path:    /g_salle
    defaults: { _controller: PlanningUserBundle:Planning:gestionsalle}
    
gestion_cours:
    path:    /g_cours
    defaults: { _controller: PlanningUserBundle:Planning:gestioncours}
    
suppression_promo:
    path:    /g_promo/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressionpromo}
    
suppression_cours:
    path:    /g_cours/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressioncours}
    
suppression_eleve:
    path:    /g_eleve/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressioneleve}
    
suppression_professeur:
    path:    /g_professeur/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressionprofesseur}
    
suppression_matiere:
    path:    /g_matiere/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressionmatiere}
    
suppression_salle:
    path:    /g_salle/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressionsalle}
    
suppression_site:
    path:    /g_site/delating
    defaults: { _controller: PlanningUserBundle:Planning:suppressionsite}
    
create:
    path:    /create
    defaults: { _controller: PlanningUserBundle:Planning:create}

register:
    path:    /register
    defaults: { _controller: PlanningUserBundle:Planning:register}
    