Eleve:
    type: entity
    table: eleve
    id:
        ideleve:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        prenom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
