Eleve:
    type: entity
    table: eleve
    indexes:
        fk_eleve_user1_idx:
            columns:
                - user_id
        fk_eleve_promotion1_idx:
            columns:
                - promotion_idpromotion
    id:
        ideleve:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        prenom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        promotionpromotion:
            targetEntity: Promotion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                promotion_idpromotion:
                    referencedColumnName: idpromotion
            orphanRemoval: false
    lifecycleCallbacks: {  }
