Promotion:
    type: entity
    table: promotion
    indexes:
        fk_promotion_eleve1_idx:
            columns:
                - eleve_ideleve
    id:
        idpromotion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numPromotion:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: num_promotion
    manyToOne:
        eleveeleve:
            targetEntity: Eleve
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                eleve_ideleve:
                    referencedColumnName: ideleve
            orphanRemoval: false
    lifecycleCallbacks: {  }
