Promotion:
    type: entity
    table: promotion
    id:
        idpromotion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numPromotion:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: num_promotion
    lifecycleCallbacks: {  }
