Salle:
    type: entity
    table: salle
    id:
        idsalle:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numSalle:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: num_salle
        nbPc:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: nb_PC
    lifecycleCallbacks: {  }
