Salle:
    type: entity
    table: salle
    indexes:
        fk_salle_cours1_idx:
            columns:
                - cours_idcours
    id:
        idsalle:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numSalle:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: num_salle
        occuper:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    manyToOne:
        courscours:
            targetEntity: Cours
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cours_idcours:
                    referencedColumnName: idcours
            orphanRemoval: false
    lifecycleCallbacks: {  }
