Site:
    type: entity
    table: site
    id:
        idsite:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idSite
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
