User:
    type: entity
    table: user
    uniqueConstraints:
        UNIQ_2DA17977F85E0677:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        salt:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        roles:
            type: array
            nullable: true
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
